// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8vaCyACFoPdTZ6C7XVSDuQOOGNAbJTDk',
    appId: '1:1018793217116:web:57f8d33521b025af52ea99',
    messagingSenderId: '1018793217116',
    projectId: 'fir-auth-8b34c',
    authDomain: 'fir-auth-8b34c.firebaseapp.com',
    storageBucket: 'fir-auth-8b34c.appspot.com',
    measurementId: 'G-5S7MQ11Y3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHWWYkpbE7uC7QgIvGfa4lpxnnUZCxlxI',
    appId: '1:1018793217116:android:510339a2f79ee57152ea99',
    messagingSenderId: '1018793217116',
    projectId: 'fir-auth-8b34c',
    storageBucket: 'fir-auth-8b34c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD899MXmZDdoIZ772Bp1NLBO9JI_oK7z_0',
    appId: '1:1018793217116:ios:c4ebc1fd42c9c26352ea99',
    messagingSenderId: '1018793217116',
    projectId: 'fir-auth-8b34c',
    storageBucket: 'fir-auth-8b34c.appspot.com',
    iosBundleId: 'com.example.form',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD899MXmZDdoIZ772Bp1NLBO9JI_oK7z_0',
    appId: '1:1018793217116:ios:c4ebc1fd42c9c26352ea99',
    messagingSenderId: '1018793217116',
    projectId: 'fir-auth-8b34c',
    storageBucket: 'fir-auth-8b34c.appspot.com',
    iosBundleId: 'com.example.form',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8vaCyACFoPdTZ6C7XVSDuQOOGNAbJTDk',
    appId: '1:1018793217116:web:27436cb90b508e3952ea99',
    messagingSenderId: '1018793217116',
    projectId: 'fir-auth-8b34c',
    authDomain: 'fir-auth-8b34c.firebaseapp.com',
    storageBucket: 'fir-auth-8b34c.appspot.com',
    measurementId: 'G-ZLM7WF7MGY',
  );
}
